[package]
name = "cras-sys"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
audio_streams = { path = "../../../audio_streams" } # provided by ebuild
data_model = { path = "../../../../../platform/crosvm/data_model" } # provided by ebuild
