[package]
name = "cras_dlc"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
anyhow = "1.0.32"
dbus = "0.9"
libc = "0.2.44"
log = "0.4.17"
once_cell = "1.17.0"
protobuf = "3.2"
system_api = { version = "*", optional = true }
thiserror = "1.0.20"

[features]
dlc = ["system_api"]
